version: '3.4'

services:

  # Contains the chrome browser, chromedriver
  chrome:
    image: selenium/standalone-chrome-debug
    # networks:
    #   - sel
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  # Contains PHP webdriver library
  php7:
    build:
      context: .
      dockerfile: ./Dockerfile
    # networks:
    #   - sel
    volumes:
      - .:/wdir/
    depends_on:
      - chrome
    command: tail -F anything

# networks:
#   sel:
# #    name: sel