version: '3.4'

services:

  # Contains the chrome browser, chromedriver
  chrome:
    # image: selenium/standalone-chrome:89.0.4389.90-chromedriver-89.0.4389.23-20210315
    image:  selenium/standalone-chrome-debug:3.141.59-20210128
    # networks:
    #   - sel
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  # Contains PHP webdriver library
  php7:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/wdir/
    depends_on:
      - chrome